# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_modpack_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 205)
        Form.setMinimumSize(QtCore.QSize(400, 205))
        Form.setMaximumSize(QtCore.QSize(400, 205))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/frog_launcher_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.pushButton_create = QtWidgets.QPushButton(Form)
        self.pushButton_create.setGeometry(QtCore.QRect(270, 80, 111, 111))
        self.pushButton_create.setObjectName("pushButton_create")
        self.lineEdit_id = QtWidgets.QLineEdit(Form)
        self.lineEdit_id.setGeometry(QtCore.QRect(10, 10, 371, 22))
        self.lineEdit_id.setInputMask("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.lineEdit_title_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_title_name.setGeometry(QtCore.QRect(10, 40, 371, 22))
        self.lineEdit_title_name.setObjectName("lineEdit_title_name")
        self.information = QtWidgets.QLabel(Form)
        self.information.setGeometry(QtCore.QRect(10, 80, 241, 121))
        self.information.setScaledContents(True)
        self.information.setWordWrap(True)
        self.information.setObjectName("information")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_create.setText(_translate("Form", "Создать модпак"))
        self.lineEdit_id.setPlaceholderText(_translate("Form", "ID модпака, например -> exampleModPack или beautfiulPack"))
        self.lineEdit_title_name.setPlaceholderText(_translate("Form", "Название модпака (необязательно)"))
        self.information.setText(_translate("Form", "<html><head/><body><p>Внимания! При создание модпака учитывайте что: имя пользователя, джава и версия клиента уникальны для каждого модпака! И задаются в настройках в главном меню лаунчера.</p><p>Спасибо за внимания :)</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
