# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 245)
        Form.setMinimumSize(QtCore.QSize(300, 245))
        Form.setMaximumSize(QtCore.QSize(300, 245))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/frog_launcher_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.top_image = QtWidgets.QLabel(Form)
        self.top_image.setGeometry(QtCore.QRect(0, 0, 301, 91))
        self.top_image.setText("")
        self.top_image.setPixmap(QtGui.QPixmap("assets/emptybanner.png"))
        self.top_image.setObjectName("top_image")
        self.comboBoxLoader = QtWidgets.QComboBox(Form)
        self.comboBoxLoader.setGeometry(QtCore.QRect(60, 130, 231, 22))
        self.comboBoxLoader.setPlaceholderText("")
        self.comboBoxLoader.setObjectName("comboBoxLoader")
        self.comboBoxVersion = QtWidgets.QComboBox(Form)
        self.comboBoxVersion.setGeometry(QtCore.QRect(60, 150, 231, 22))
        self.comboBoxVersion.setEditable(False)
        self.comboBoxVersion.setCurrentText("")
        self.comboBoxVersion.setPlaceholderText("")
        self.comboBoxVersion.setObjectName("comboBoxVersion")
        self.lineEditPlayerName = QtWidgets.QLineEdit(Form)
        self.lineEditPlayerName.setGeometry(QtCore.QRect(10, 181, 161, 21))
        self.lineEditPlayerName.setObjectName("lineEditPlayerName")
        self.pushButtonDone = QtWidgets.QPushButton(Form)
        self.pushButtonDone.setGeometry(QtCore.QRect(175, 180, 120, 50))
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 130, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 61, 20))
        self.label_2.setObjectName("label_2")
        self.lineEditVisualName = QtWidgets.QLineEdit(Form)
        self.lineEditVisualName.setGeometry(QtCore.QRect(10, 100, 281, 21))
        self.lineEditVisualName.setObjectName("lineEditVisualName")
        self.lineEditJavaArgs = QtWidgets.QLineEdit(Form)
        self.lineEditJavaArgs.setGeometry(QtCore.QRect(10, 210, 161, 21))
        self.lineEditJavaArgs.setObjectName("lineEditJavaArgs")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEditPlayerName.setPlaceholderText(_translate("Form", "Имя игрока"))
        self.pushButtonDone.setText(_translate("Form", "Применить"))
        self.label.setText(_translate("Form", "Лоадер:"))
        self.label_2.setText(_translate("Form", "Версия:"))
        self.lineEditVisualName.setPlaceholderText(_translate("Form", "Визуальное название сборки"))
        self.lineEditJavaArgs.setPlaceholderText(_translate("Form", "Аргументы Java"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
