from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(495, 195)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(495, 195))
        MainWindow.setMaximumSize(QtCore.QSize(495, 195))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/frog_launcher_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run.setGeometry(QtCore.QRect(10, 140, 281, 45))
        self.pushButton_run.setObjectName("pushButton_run")
        self.top_image = QtWidgets.QLabel(self.centralwidget)
        self.top_image.setGeometry(QtCore.QRect(-10, 0, 301, 91))
        self.top_image.setText("")
        self.top_image.setPixmap(QtGui.QPixmap("assets/emptybanner.png"))
        self.top_image.setObjectName("top_image")
        self.pushButton_folder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_folder.setGeometry(QtCore.QRect(130, 100, 40, 40))
        self.pushButton_folder.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_folder.setIcon(icon1)
        self.pushButton_folder.setObjectName("pushButton_folder")
        self.pushButton_config = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_config.setGeometry(QtCore.QRect(90, 100, 40, 40))
        self.pushButton_config.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_config.setIcon(icon2)
        self.pushButton_config.setObjectName("pushButton_config")
        self.pushButton_reload = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reload.setGeometry(QtCore.QRect(170, 100, 40, 40))
        self.pushButton_reload.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_reload.setIcon(icon3)
        self.pushButton_reload.setObjectName("pushButton_reload")
        self.pushButton_download = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_download.setGeometry(QtCore.QRect(50, 100, 40, 40))
        self.pushButton_download.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_download.setIcon(icon4)
        self.pushButton_download.setObjectName("pushButton_download")
        self.pushButton_create = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_create.setGeometry(QtCore.QRect(10, 100, 40, 40))
        self.pushButton_create.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("assets/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_create.setIcon(icon5)
        self.pushButton_create.setObjectName("pushButton_create")
        self.list_view = QtWidgets.QListWidget(self.centralwidget)
        self.list_view.setGeometry(QtCore.QRect(300, 0, 181, 191))
        self.list_view.setObjectName("list_view")
        self.pushButton_log = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_log.setGeometry(QtCore.QRect(210, 100, 40, 40))
        self.pushButton_log.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("assets/notepad.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_log.setIcon(icon6)
        self.pushButton_log.setObjectName("pushButton_log")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(250, 100, 40, 40))
        self.pushButton_exit.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("assets/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exit.setIcon(icon7)
        self.pushButton_exit.setObjectName("pushButton_exit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FLauncher"))
        self.pushButton_run.setText(_translate("MainWindow", "Запустить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
