# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(195, 105)
        Form.setMinimumSize(QtCore.QSize(195, 105))
        Form.setMaximumSize(QtCore.QSize(195, 105))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/frog_launcher_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.installLineEdit = QtWidgets.QLineEdit(Form)
        self.installLineEdit.setGeometry(QtCore.QRect(10, 10, 171, 21))
        self.installLineEdit.setObjectName("installLineEdit")
        self.installPushButton = QtWidgets.QPushButton(Form)
        self.installPushButton.setGeometry(QtCore.QRect(10, 40, 171, 51))
        self.installPushButton.setObjectName("installPushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.installLineEdit.setPlaceholderText(_translate("Form", "Какой модпак поставить?"))
        self.installPushButton.setText(_translate("Form", "Установить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
